FROM docker.io/vllm/vllm-openai:nightly

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake ninja-build git pkg-config \
    python3-dev libssl-dev libcurl4-openssl-dev ca-certificates curl \
  && rm -rf /var/lib/apt/lists/*

ENV CUDA_HOME=/usr/local/cuda
ENV PATH="${CUDA_HOME}/bin:${PATH}"

# Speed up builds
RUN pip install -U pip setuptools wheel cmake && pip uninstall -y lmcache

# (A) Build from Git tag (recommended)
RUN TORCH_CUDA_ARCH_LIST="8.9+PTX;10.0+PTX;12.0+PTX" pip install --no-binary=:all: --no-deps --no-build-isolation \
    "git+https://github.com/LMCache/LMCache.git@v0.3.9#egg=lmcache"

# (Optional but helpful) enable TF32 for some ops
ENV TORCH_ALLOW_TF32_CUBLAS=1 \
    TORCH_CUDNN_ALLOW_TF32=1

COPY "E=128,N=1408,device_name=NVIDIA_RTX_PRO_6000_Blackwell_Workstation_Edition,dtype=fp8_w8a8.json" /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs
COPY "E=96,N=1408,device_name=NVIDIA_RTX_PRO_6000_Blackwell_Workstation_Edition,dtype=fp8_w8a8.json" /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs
