name: Build and Push Container

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Set start time
      run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v5

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | podman login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build the container
      run: |
        podman build -t malaiwah/vllm-lmcache-cu128:uv312 -f Containerfile .

    - name: Push the container
      run: |
        podman push malaiwah/vllm-lmcache-cu128:uv312

    - name: Log image size
      run: |
        size=$(podman inspect malaiwah/vllm-lmcache-cu128:uv312 --format "{{.Size}}")
        echo "Image size: $(($size / 1024 / 1024)) MB"

    - name: Install Cosign
      run: |
        mkdir -p bin
        curl -L https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o bin/cosign
        chmod +x bin/cosign

    - name: Sign the image
      run: |
        echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
        bin/cosign sign --key cosign.key --yes --registry-username ${{ secrets.DOCKERHUB_USERNAME }} --registry-password ${{ secrets.DOCKERHUB_TOKEN }} malaiwah/vllm-lmcache-cu128:uv312
        rm cosign.key
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

    - name: Log build time
      run: |
        end_time=$(date +%s)
        build_time=$((end_time - START_TIME))
        echo "Build time: $build_time seconds"

  test:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Cosign
      run: |
        mkdir -p bin
        curl -L https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o bin/cosign
        chmod +x bin/cosign

    - name: Verify signature
      run: |
        bin/cosign verify --key cosign.pub malaiwah/vllm-lmcache-cu128:uv312

    - name: Run test
      run: |
        chmod +x test.sh
        ./test.sh

    - name: Upload Test Output
      uses: actions/upload-artifact@v4
      with:
        name: test_output
        path: test_output.txt
