name: Build and Push Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | podman login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build the container
      run: |
        podman build -t malaiwah/vllm-lmcache-cu128:uv312 -f Containerfile .

    - name: Push the container
      run: |
        podman push malaiwah/vllm-lmcache-cu128:uv312

    - name: Install Cosign
      run: |
        curl -L https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o cosign
        chmod +x cosign
        sudo mv cosign /usr/local/bin/

    - name: Sign the image
      run: |
        echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
        cosign sign --key cosign.key --yes --registry-username ${{ secrets.DOCKERHUB_USERNAME }} --registry-password ${{ secrets.DOCKERHUB_TOKEN }} malaiwah/vllm-lmcache-cu128:uv312
        rm cosign.key
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

  test:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run test
      run: |
        chmod +x test.sh
        ./test.sh

    - name: Commit test output
      run: |
        git add test_output.txt
        git commit -m "Add test output from model inference" || echo "No changes to commit"