name: Build and Push Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | podman login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build the container
      run: |
        podman build -t malaiwah/vllm-lmcache-cu128:uv312 -f Containerfile .

    - name: Push the container
      run: |
        podman push malaiwah/vllm-lmcache-cu128:uv312
        digest=$(podman inspect malaiwah/vllm-lmcache-cu128:uv312 | jq -r '.RepoDigests[0]' | cut -d'@' -f2)
        echo "DIGEST=$digest" >> $GITHUB_ENV

    - name: Install Cosign
      run: |
        curl -L https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o cosign
        chmod +x cosign
        sudo mv cosign /usr/local/bin/

    - name: Sign the image
      run: |
        echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
        cosign sign --key cosign.key --yes --registry-username ${{ secrets.DOCKERHUB_USERNAME }} --registry-password ${{ secrets.DOCKERHUB_TOKEN }} malaiwah/vllm-lmcache-cu128@$DIGEST
        rm cosign.key
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}